# Generated by Django 2.2.1 on 2019-07-21 21:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorityname', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'priorities',
                'db_table': 'priority',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusname', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'statuses',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=255)),
                ('taskdescription', models.TextField(blank=True, null=True)),
                ('dateentered', models.DateField(default=datetime.date(2019, 7, 21))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='houseapp.Category')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='houseapp.Priority')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='houseapp.Status')),
            ],
            options={
                'verbose_name_plural': 'tasks',
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtitle', models.CharField(max_length=255)),
                ('logdate', models.DateField(default=datetime.date(2019, 7, 21))),
                ('logEntry', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='houseapp.Task')),
            ],
            options={
                'verbose_name_plural': 'tasklogs',
                'db_table': 'tasklog',
            },
        ),
    ]
