# Generated by Django 2.2.1 on 2019-07-21 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateentered',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='logdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
